services:
  go:
    build:
      context: ./dockerfiles/
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./src:/src
    networks:
      fidrant_network:
        ipv4_address: 172.22.1.2

  db:
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      fidrant_network:
        ipv4_address: 172.22.1.3

  nginx:
    image: nginx:1.25
    ports:
      - 80:80
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go
    networks:
      fidrant_network:
        ipv4_address: 172.22.1.4

networks:
  fidrant_network:
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
          gateway: 172.22.1.1
